version: '3'

services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: lucaslz/nginx:prod
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"

  app:
    build:
      context: node
    image: lucaslz/app:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/database.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge