version: '3'

services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: lucaslz/nginx:prod
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: lucaslz/app:prod
    container_name: app
    command: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - ./usr/src/app/node_volumes
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge